# Use the official Node.js 16 LTS image as a parent image
FROM node:20.0.0-alpine AS backend

# Set the working directory for backend
WORKDIR /app/quirknotes/backend

# Copy package.json and package-lock.json files
COPY quirknotes/backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of your application's code
COPY quirknotes/backend ./

# Your app binds to port 3000 so you'll use the EXPOSE instruction to have it mapped by the docker daemon
EXPOSE 3000

# Define the command to run your app using CMD which defines your runtime
CMD [ "npm", "run", "dev"]
